environment:
  matrix:
    - TARGET: 1.5.0-i686-pc-windows-gnu
    - TARGET: 1.2.0-i686-pc-windows-gnu

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe"
  - rust-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
